//export const LOGIN = 'LOGIN'
export const RESET_APP_STATE = 'RESET_APP_STATE'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const STORE_SESSION_DATA = 'STORE_SESSION_DATA'
export const STORE_SESSION_EXPIRATION = 'STORE_SESSION_EXPIRATION'
export const UPDATE_SESSION_TOKEN = 'UPDATE_SESSION_TOKEN'

export const UPDATE_LOCAL_INVENTORY = 'UPDATE_LOCAL_INVENTORY'
export const UPDATE_LOCAL_INVENTORY_ITEM = 'UPDATE_LOCAL_INVENTORY_ITEM'

export const LOAD_INVENTORY = 'LOAD_INVENTORY'
export const UPDATE_INVENTORY_ITEM = 'UPDATE_INVENTORY_ITEM'

export const ADD_SORT = 'ADD_SORT'
export const REMOVE_SORT = 'REMOVE_SORT'
export const ADD_FILTER = 'ADD_FILTER'
export const REMOVE_FILTER = 'REMOVE_FILTER'
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER'

export const FETCH_DATA = 'FETCH_DATA'
export const FETCH_DATA_FROM_API = 'FETCH_DATA_FROM_API'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'


export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'